In [1]:
import tensorflow as tf

In [2]:
ylist = []
y1 = tf.ones([3, 3])
ylist.append(y1)
y2 = tf.ones([3, 3])
ylist.append(y2)
y3 = tf.ones([3, 3])
ylist.append(y3)

In [3]:
ylist

[<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>]

In [4]:
tf.add_n(ylist)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], dtype=float32)>